// Typed REST API helpers for fetching Payload collections from the client side or during ISR.
// Types are placeholders until payload-types.ts is generated by `npm run generate:types`.

const BASE_URL = process.env.NEXT_PUBLIC_SERVER_URL || 'http://localhost:3000'

async function fetchAPI<T>(path: string, options?: RequestInit): Promise<T> {
  const res = await fetch(`${BASE_URL}/api${path}`, {
    headers: { 'Content-Type': 'application/json' },
    ...options,
  })
  if (!res.ok) {
    throw new Error(`API error ${res.status}: ${path}`)
  }
  return res.json() as Promise<T>
}

export async function getProducts(params?: {
  where?: Record<string, unknown>
  limit?: number
  page?: number
}): Promise<{ docs: unknown[]; totalDocs: number; totalPages: number }> {
  const query = new URLSearchParams()
  query.set('where[websiteVisible][equals]', 'true')
  if (params?.limit) query.set('limit', String(params.limit))
  if (params?.page) query.set('page', String(params.page))
  return fetchAPI(`/products?${query}`)
}

export async function getProduct(slug: string): Promise<unknown> {
  const query = new URLSearchParams()
  query.set('where[slug][equals]', slug)
  query.set('where[websiteVisible][equals]', 'true')
  query.set('limit', '1')
  const result = await fetchAPI<{ docs: unknown[] }>(`/products?${query}`)
  return result.docs[0] ?? null
}

export async function getPage(slug: string): Promise<unknown> {
  const query = new URLSearchParams()
  query.set('where[slug][equals]', slug)
  query.set('limit', '1')
  const result = await fetchAPI<{ docs: unknown[] }>(`/pages?${query}`)
  return result.docs[0] ?? null
}

export async function getSiteNavigation(): Promise<unknown> {
  return fetchAPI('/globals/site-navigation')
}

export async function getSiteFooter(): Promise<unknown> {
  return fetchAPI('/globals/site-footer')
}

export async function submitDistributorApplication(
  data: Record<string, unknown>,
): Promise<unknown> {
  return fetchAPI('/distributor-applications', {
    method: 'POST',
    body: JSON.stringify(data),
  })
}
